repos:
  - repo: https://github.com/astro/deadnix
    rev: v1.2.1
    hooks:
      - id: deadnix
        name: Scan Nix files for dead code
        args:
          - --edit
          - --no-lambda-arg
        stages: [pre-commit]
  # - repo: https://github.com/nix-community/nixpkgs-fmt
  #   rev: v1.3.0
  #   hooks:
  #     - id: nixpkgs-fmt
  #       name: Format nix code with nixpkgs-fmt
  #       stages: [pre-commit]
