{ config, lib, pkgs, ... }:

let
  cfg = config.tsrk.shell.fastfetch;
in
{
  options = {
    tsrk.shell.fastfetch = {
      enable = lib.options.mkEnableOption "FastFetch";
      package = lib.options.mkPackageOption pkgs "FastFetch" {
        default = [ "fastfetch" ];
      };
      config = lib.options.mkOption {
        type = lib.types.attrs;
        description = ''
          Configuration for FastFetch

          Refer to https://github.com/fastfetch-cli/fastfetch/wiki/Json-Schema for definitions
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile."fastfetch/config.jsonc".text = ''
      // Generated by Home-Manager
      ${builtins.toJSON cfg.config}
    '';

    programs.zsh.initExtra = ''
      ${cfg.package}/bin/fastfetch
      '';

    home.packages = [ cfg.package ];
  };
}
