{ config, lib, pkgs, ... }:

let
  fastFetchConfig = {
    modules = [
      "title"
      "separator"
      "os"
      "host"
      "packages"
      "wm"
      "terminal"
      "display"
      "cpu"
      "gpu"
      "break"
      "break"
      "colors"
    ];
  };
in
{
  programs.zsh.enable = true;
  programs.zsh.shellAliases = {
    l = "lsd -lah";
    lg = "lazygit";
    ls = "lsd";
    cd = "z";
  };
  programs.zsh.enableAutosuggestions = true;
  programs.zsh.syntaxHighlighting.enable = true;
  programs.zsh.autocd = true;

  programs.zsh.initExtra = ''
    bindkey -v
    ${pkgs.fastfetch}/bin/fastfetch
  '';

  xdg.configFile."fastfetch/config.jsonc".text = ''
    // Generated by Home-Manager
    ${builtins.toJSON fastFetchConfig}
  '';
}
