{ config, lib, pkgs, ... }:

let
  fastFetchConfig = {
    modules = [
      "title"
      "separator"
      "os"
      "host"
      "packages"
      "wm"
      "terminal"
      "display"
      "cpu"
      "gpu"
      "break"
      "break"
      "colors"
    ];
  };
in
{
  programs.zsh = {
    enable = true;
    shellAliases = {
      l = "lsd -lah";
      lg = "lazygit";
      ls = "lsd";
      cd = "z";
    };
    enableAutosuggestions = true;
    syntaxHighlighting.enable = true;
    historySubstringSearch.enable = true;
    autocd = true;

    initExtra = ''
      bindkey -v
      ${pkgs.fastfetch}/bin/fastfetch
      '';
  };

  xdg.configFile."fastfetch/config.jsonc".text = ''
    // Generated by Home-Manager
    ${builtins.toJSON fastFetchConfig}
  '';
}
