[
  ./network/hostname.nix
  ./network/networkmanager.nix
  ./packages
  ./programs/gamescope.nix
  ./services/audio.nix
  ./services/audio/mopidy
  ./services/hardware/bluetooth.nix
  ./services/hardware/disks.nix
  ./services/networking/sshd
  ./services/virtualisation/containers
  ./services/virtualisation/libvirt.nix
  ./services/x11/dipslay-manager/sddm.nix
  ./services/x11/keyboard/qwerty-fr.nix
  ./services/x11/redshift.nix
  ./services/x11/sessions/i3.nix
  ./services/x11/sessions/hyprland.nix
]
