[
  ./network/hostname.nix
  ./packages
  ./services/audio.nix
  ./services/hardware/bluetooth.nix
  ./services/hardware/disks.nix
  ./services/virtualisation/containers
  ./services/x11/dipslay-manager/sddm.nix
  ./services/x11/keyboard/qwerty-fr.nix
  ./services/x11/sessions/i3.nix
]
