[
  ./desktop/darkman.nix
  ./desktop/dunst.nix
  ./desktop/flameshot.nix
  ./desktop/i3.nix
  ./desktop/kitty.nix
  ./desktop/music-player.nix
  ./desktop/picom.nix
  ./desktop/polybar.nix
  ./desktop/premid.nix
  ./desktop/rofi.nix
  ./desktop/thunderbird.nix
  ./desktop/xdg.nix
  ./desktop/xsettingsd.nix
  ./epita
  ./git
  ./nvim
  ./packages
  ./shell
  ./ssh.nix
]
